### ISSUE TITLE
Rename AB auth decorator

### ISSUE THREAD

**Issue by ericclack** [brightinteractive/asset-bank-auth-django#1]
This sounds like a boolean to me:
@is_assetbank_authenticated_user

How about:
@user_is_assetbank_authenticated
Or
@ensure_assetbank_authenticated_user

Copied from:
https://github.com/brightinteractive/django-react-starter-app/issues/22

**Comment by kevinbennett** [comment]
Fixed in d7b678a2629986f892eb108de3fc0d1385b892c2
